# Generated by Django 3.2.12 on 2022-04-04 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
